version: 2.1
orbs:
  node: circleci/node@4.2.0
jobs:
  build-and-test:
    executor: 
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: cd ClientApp && npm install
            - run: cd ClientApp && npm test
workflows: 
  test:
    jobs:
      - build-and-test